spring:
  datasource:
    url: jdbc:postgresql://localhost:4200/gardenstore_db
    username: cedric
    password: Artterrevil-85
    driver-class-name: com.postgresql.Driver
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    format_sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    allow-circular-references: true

server:
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    path: /v3/api-doc
  swagger-ui:
    path: /swagger-ui