spring:
  datasource:
    url: jdbc:postgresql://localhost:4200/gardenstore_db
    username: cedric
    password: Artterrevil-85
    driver-class-name: com.postgresql.Driver
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

    allow-circular-references: true

server:
  port: 8080
  format_sql: true

springdoc:
  api-docs:
    path: /v3/api-doc
  swagger-ui:
    path: /swagger-ui