spring:
  datasource:
    url: jdbc:postgresql://localhost:4200/gardenstore_db
    username: cedric
    password: Artterrevil-85
    driver-class-name: com.postgresql.Driver
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    format_sql: true
    properties:
      hibernate:

    allow-circular-references: true

server:
  port: 8080
