version: "3.9"
services:
    backend:
        image: nginx:latest
        container_name: MyBackendApp
        build:
            context: ./MyBackendApp
        ports:
            - "8080:80"
    frontend:
        image: postgres:latest
        container_name: Frontend
        build:
            context: ./Frontend
        ports:
            - "4200:80"
        depends_on:
            - backend

